#!/bin/tcsh
#
# This script will update the user's path to make their current terminal session use
# the origen executable from the local workspace containing this script, rather than
# the default version from elsewhere.
# 
#       > source source_setup
#
set called=($_)

set called_dir = $PWD            # Directory from which this script was called
set relative_path = $called[2]   # Relative path from there to this file     
set origen_install = `dirname $called_dir/$relative_path`  
set origen_bin = $origen_install/bin      

# Add the origen bin dirs to the user's path as highest priority
setenv PATH ./lbin\:$origen_bin\:$PATH
