# This is an example pattern source, you can create a pattern description like this:

$desc =<<END
This is an example pattern generated by Origen!
It downloads an s-record to a dummy device.
END

# If you have a simple one-line description you can use regular string assignment syntax:
# $desc = "This is a one-line description of my pattern"

# You can also leave out the description if you like, or if you want to pick up some
# dynamic values you can embed it within the pattern block below.

# The pattern code starts here...
Pattern.create do

    $dut.download_srec("lib/example.abs.S19")
    
    # Time periods defined via multiple options like this will be added together,
    # in this case because the match option is enabled it will define the maximum
    # wait time
    $tester.wait(:time_in_us => 20, :time_in_ms => 100, :cycles => 100,
                 :match => true, :pin => $dut.pin(:fail), :state => :high) 

    $dut.reg(:control).bit(:fail).read!

end
