name: Origen Core Regression Tests - Ruby 3
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        ruby-version: [3.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update Env
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    - name: Install Bundler
      run: gem install bundler -v '> 2'
    - name: Remove Gemfile.lock
      run: rm Gemfile.lock
    - name: Install dependencies
      run: bundle install
    - name: Build Origen Gem
      run: gem build origen.gemspec --output origen.gem    
    - name: Gem Install Origen 
      run: gem install origen.gem 
    - name: Setup Dependencies
      run: origen -v
    - name: Set Origen to debug mode
      run: origen m debug
    - name: Run Spec tests
      run: origen test -c
